### PR TITLE
Fix usage of AppDelegateSwizzler

### LINKED ISSUE #79: Found outdated dependencies.
GoogleUtilities: new version available 6.7.2 -> (unused) (latest version 7.0.0)

### PR DESCRIPTION
**Pull request by yatatsu**
Fix #79 

- Update `GoogleUtilities/AppDelegateSwizzler` to 7.0
  - https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/CHANGELOG.md#700
- Initialize AppDelegateInterceptor in the UIThread.
- Use `React-Core` instead of `React` for Xcode 12 (see https://github.com/facebook/react-native/issues/29633 ).
- Fix ignoring interceptor because of missing implementation of `application:openURL:sourceApplication:annotation`.
  - https://github.com/firebase/firebase-ios-sdk/blob/master/GoogleUtilities/AppDelegateSwizzler/README.md

### CODE REVIEW

File: ios/Classes/RNPAYCore.m [hunk 1]
```diff
@@ -28,6 +28,10 @@
 
 @implementation RNPAYCore
 
+- (dispatch_queue_t)methodQueue {
```
Comment (natsuki-yamanaka) [inline ios/Classes/RNPAYCore.m:31]: https://reactnative.dev/docs/native-modules-ios#threading 
ここら辺に書いてあるやり方かな。よさそう

**Review by natsuki-yamanaka — APPROVED** [review]
